FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /carbonzero-user-management-dir

COPY ./carbonzero_user_management/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./carbonzero_user_management/. .

ENTRYPOINT ["sh", "/carbonzero-user-management-dir/entrypoint.sh"]