FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED=1

WORKDIR /carbonzero-user-management-dir

COPY ./carbonzero_user_management/requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY ./carbonzero_user_management/. .

COPY ./carbonzero_integration/carbonzero_common .

CMD python3 manage.py makemigrations && \
    python3 manage.py migrate && \
    python3 manage.py runserver 0.0.0.0:8001