# Generated by Django 4.2.1 on 2023-08-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unit',
            field=models.CharField(default='gram', max_length=50),
            preserve_default=False,
        ),
    ]
